wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.32
    code_path: code/Multilayer-Perceptron-Experiments/DeepFM-PyTorch/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.4
